controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

movie_show:
    path: /movie/{tmdbId}
    controller: App\Controller\MediaController::show
    requirements:
        tmdbId: \d+
